version: 0.2
os: linux
files:
  - source: target/transaction-recorder.war
    destination: /opt/tomcat/webapps/
hooks:
  BeforeInstall:
    - location: ./scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: ./scripts/start_tomcat.sh
      timeout: 300
      runas: root
